import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import LinkButton from '@/components/Button/LinkButton';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body className={`min-h-screen ${inter.className}`}>
        <div className='max-w-4xl mx-auto py-10 px-4'>
          <Header />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
