import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import LinkButton from '@/components/LinkButton';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='px-4 lg:px-48 py-8'>
          {children}
          <div className='flex space-x-3'>
            <LinkButton
              href='/'
              className='
              mt-10 bg-blue-400 hover:bg-blue-300 w-20 h-12'
            >
              ホーム
            </LinkButton>
          </div>
        </main>
      </body>
    </html>
  );
}
